trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.9.0'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/parent_module'
      backendServiceArm: 'azure-terraform'
      backendAzureRmResourceGroupName: '<resource-group-name>'
      backendAzureRmStorageAccountName: '<storage-account-name>'
      backendAzureRmContainerName: '<container-name>'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/parent_module'
      environmentServiceNameAzureRM: 'azure-terraform'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/parent_module'
      environmentServiceNameAzureRM: 'azure-terraform'